info:
  version: "Micro-config 1.0"
server:
  port: 7003
spring:
  profiles:
    active: dev,native
  application:
    name: Micro-config
    
---
spring:
  profiles: dev,native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
eureka:
  instance:
    preferIpAddress: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/      
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
logging:
  file: C:/log/boeConfig.log
  level.root: INFO